# eureka客户端（即服务提供者）,集群
spring:
  application:
    name: eureka-client
  profiles:
    active: peer1  
    
  # 数据源配置  
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root1234
    
  # Spring data JPA配置
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true     
  
  # zipkin 配置
  zipkin: 
    base-url: http://localhost:8720  # 指定了Zipkin服务器的地址
    
  # sleuth 配置    
  sleuth:
    sampler:
      percentage: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
        
# 服务器配置
server:
  # 指定该Eureka实例的端口
  port: 8760
  
# eureka服务配置
eureka:
  # instance:
    # hostname: eureka-client1
  client:
    serviceUrl:
      # 注册到高可用的服务中心（集群）
      # 无认证
      # defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
      # 需认证版（规则：http://user:password@host:port/eureka/）
      defaultZone: http://eureka_admin:eureka_admin_123@peer1:8761/eureka/,http://eureka_admin:eureka_admin_123@peer2:8762/eureka/,http://eureka_admin:eureka_admin_123@peer3:8763/eureka/



