# 单个eureka服务中心
spring:
  application:
    name: eureka-server

# 服务器配置
server:
  # 指定该Eureka实例的端口
  port: 8761
  
# eureka服务配置
eureka:
  instance:
    hostname: eureka-server
  server:
    # 关闭自我保护
    enableSelfPreservation: false  
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    registerWithEureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



