# eureka服务集群peer3
# 服务器配置
server:
  # 指定该Eureka实例的端口
  port: 8763
  
# eureka配置  
eureka:
  client:
    serviceUrl:
      # 注册到peer1,peer2上
      # defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      # 需认证版（规则：http://user:password@host:port/eureka/）
      defaultZone: http://eureka_admin:eureka_admin_123@peer1:8761/eureka/,http://eureka_admin:eureka_admin_123@peer2:8763/eureka/